#!/bin/bash
# Author: mr_floki
# Date Created: 13/02/2021
# Description: Copy and Rename a batch of files
# Date Modified: 15/02/2021

clear

mkdir copy
for i in {1..5}; do
	mkdir copy/s0$i
done

i=1
s1=49
s2=97
s3=144
s4=184

for filename in *.mkv; do
        f=`echo "$filename" | cut -d ' ' -f 5-`
	n=`echo "$filename" | cut -d ' ' -f 4`

	# Season 1
	if [ $n -le $s1 ]; then
		cp "$filename" "copy/s01/$n $f"
	
	# Season 2
	elif [ $n -gt $s1 ] && [ $n -le $s2 ]; then
		cp "$filename" "copy/s02/$((n-$s1)) $f"
	
	# Seson 3
	elif [ $n -gt $s2 ] && [ $n -le $s3 ]; then
		cp "$filename" "copy/s03/$((n-$s2)) $f"

	# Season 4
	elif [ $n -gt $s3 ] && [ $n -le $s4 ]; then
		cp "$filename" "copy/s04/$((n-$s3)) $f"

	# Season 5
	else
		cp "$filename" "copy/s05/$((n-$s4)) $f"
	fi
	
	# Increment
	echo Files Copied: $i
	i=$((i+1))
done
