#!/bin/bash
# Author: mr_floki
# Date Created: 16/02/2021
# Description: Show temp and other sys informations
# Date Modified: 16/02/2021

echo "--------------------------"
figlet temp
echo "--------------------------"
echo

sensors
hddtemp /dev/sd[abcd]
echo

cat /proc/driver/rtc | grep batt

cpu=$(cat /proc/cpuinfo | grep processor | wc -l)
echo "Number of CPU : $cpu"
