#!/bin/bash
# Author: mr_floki
# Date Created: 10/02/2021
# Description: Script Format Example
# Date Modified: 10/02/2021

a='mr_floki'
b=1000

echo -e "\n$a\n"

date
df -h

	if [ $b -gt 100 ]
	then
	echo Hey that\'s a large number.
	fi
