#!/bin/bash
# Author: mr_floki
# Date Created: 05/03/2021
# Description: copy file to hosts
# Date Modified: 05/03/2021

hosts="host1
Host2
Host3"
user=user
place=/place
file=/file

for host in hosts; do
	rsync $file $user@$host:$place
done
