#!/bin/bash
# Author: mr_floki
# Date Created: 18/20/2021
# Description: Ping Multiple Hosts from a List
# Date Modified: 18/02/2021

LIST=./hosts.txt

for IP in $(cat $LIST)
do
	ping -c1 $IP &> /dev/null
	if [ $? -eq 0 ]
	then
		echo "$IP is UP"
	else
		echo "$IP is Down"
	fi
done
